#!/usr/bin/env python
"""
Executes a mldb-sql query from a file
"""

import sys
from pprint import pprint

import pandas
pandas.set_option('display.max_rows', 10000)
pandas.set_option('display.max_columns', 9999)

from pymldb import Connection

def usage_and_exit():
    print('usage:')
    print(__doc__)
    print(__file__ + ' http://mldb_host:port file.sql')
    sys.exit()

if __name__ == '__main__':
    args = sys.argv[1:]
    if len(args) != 2:
        usage_and_exit()

    host, f = args

    if not host.startswith('http'):
        host = 'http://' + host

    mldb = Connection(host)

    pprint(mldb.get('/v1/query', q=open(f).read(), format='aos').json())
